---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 4096

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
    driver:
      customize:
        createhd:
          - filename: /tmp/disk1604.vmdk
            size: 60000
  - name: ubuntu-18.04
    driver:
      customize:
        createhd:
          - filename: /tmp/disk1804.vmdk
            size: 60000

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[jetbrains_test::default]
    attributes:
